# Generated by Django 2.2.7 on 2019-12-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contrasena',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='apellido',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='correo',
            new_name='las_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nombre',
            new_name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
