# Generated by Django 2.2.7 on 2019-12-04 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191204_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='las_name',
            new_name='last_name',
        ),
    ]
