# Generated by Django 2.2.7 on 2019-12-12 23:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tableros', '0009_auto_20191212_1752'),
        ('users', '0004_auto_20191212_1750'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserTableros',
        ),
    ]
