# Generated by Django 2.2.7 on 2019-12-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabled',
            name='visibility',
            field=models.CharField(choices=[('Y', 'Yes'), ('No', 'No')], max_length=1),
        ),
    ]
