# Generated by Django 2.2.7 on 2019-12-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0002_auto_20191210_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabled',
            name='visibility',
            field=models.CharField(choices=[('Pb', 'Public'), ('Pr', 'Privacy')], max_length=2),
        ),
    ]
