# Generated by Django 2.2.7 on 2019-12-11 01:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tableros', '0005_auto_20191210_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabled',
            name='favorite',
            field=models.ManyToManyField(related_name='favorite_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tabled',
            name='members',
            field=models.ManyToManyField(related_name='members_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
