# Generated by Django 2.2.7 on 2019-12-12 23:50

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0007_auto_20191211_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabled',
            name='favorite',
            field=models.ManyToManyField(null=True, related_name='favorite_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tabled',
            name='fecha_hora',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 12, 23, 50, 15, 312139, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tabled',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
