# Generated by Django 2.2.7 on 2019-12-12 23:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0008_auto_20191212_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabled',
            name='fecha_hora',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 12, 23, 52, 21, 377410, tzinfo=utc)),
        ),
    ]
