# Generated by Django 2.2.7 on 2020-03-16 22:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0009_auto_20191212_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabled',
            name='fecha_hora',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 22, 53, 48, 40905, tzinfo=utc)),
        ),
    ]
